In [17]:
import numpy as np
import pandas as pd

In [18]:
# simple python datetime object
import datetime as dt
dt.datetime(2026,9,3,11,37)

datetime.datetime(2026, 9, 3, 11, 37)

# Pandas TimeStamp

In [19]:
pd.Timestamp(dt.datetime(2026,9,3,11,37)) # using python datetime store time instant

Timestamp('2026-09-03 11:37:00')

In [20]:
# other ways
pd.Timestamp('2026/9/3')

Timestamp('2026-09-03 00:00:00')

In [21]:
pd.Timestamp(year=2026 , month=9 , day=3 , hour=11 , minute=41 )

Timestamp('2026-09-03 11:41:00')

In [12]:
pd.Timestamp("2026-9-3 11")
pd.Timestamp("2026-9-3 11:41")
pd.Timestamp("2026-9-3 11:41:00")

Timestamp('2026-09-03 11:41:00')

In [22]:
# Current time
now = pd.Timestamp.now()
now

Timestamp('2026-09-04 09:49:14.053433')

In [ ]:
# ISO-8601 / Standard datetime
pd.to_datetime("2024-05-15 14:30:00", format="%Y-%m-%d %H:%M:%S")

# US Date Format (MM/DD/YYYY)
pd.to_datetime("05/15/2024", format="%m/%d/%Y")

# European Date Format (DD/MM/YYYY)
pd.to_datetime("15-05-2024", format="%d-%m-%Y")

# Textual Month with 12-hour Clock
pd.to_datetime("May 15, 2024 02:30 PM", format="%B %d, %Y %I:%M %p")

Timestamp('2024-05-15 00:00:00')

In [32]:
date= pd.to_datetime("2026/9/3  11:30:11")
date

Timestamp('2026-09-03 11:30:11')

In [36]:
date.year
date.month
date.second

11

In [54]:
# as python datetime is slow so numpy team made a datatype for it named as datetime64
arr = np.array(['2026-09-04' ,'2026-09-05' ] , dtype=np.datetime64)
print(arr)
type(arr[0])

['2026-09-04' '2026-09-05']

numpy.datetime64

In [ ]:
arr+2 # vectorized datetime operation

array(['2026-09-06', '2026-09-07'], dtype='datetime64[D]')

In [ ]:
arr2 = np.array("2026-09-04" , dtype=np.datetime64)
arr2+ np.arange(11) # vectorized datetime operation

array(['2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07',
       '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11',
       '2026-09-12', '2026-09-13', '2026-09-14'], dtype='datetime64[D]')

# DatetimeIndex Object

**A collection of pandas timestamp**

In [63]:
temp = pd.DatetimeIndex(['2026-09-4' , '2026-09-5' , '2026-09-6'])
print(temp)
print(type(temp))
print(type(temp[0]))

DatetimeIndex(['2026-09-04', '2026-09-05', '2026-09-06'], dtype='datetime64[us]', freq=None)
<class 'pandas.DatetimeIndex'>
<class 'pandas.Timestamp'>

In [64]:
# using python datetime object
pd.DatetimeIndex([dt.datetime(2023,1,1),dt.datetime(2022,1,1),dt.datetime(2021,1,1)])

DatetimeIndex(['2023-01-01', '2022-01-01', '2021-01-01'], dtype='datetime64[us]', freq=None)

In [66]:
# using pd.timestamps
dt_index = pd.DatetimeIndex([pd.Timestamp(2023,1,1),pd.Timestamp(2022,1,1),pd.Timestamp(2021,1,1)])
dt_index

DatetimeIndex(['2023-01-01', '2022-01-01', '2021-01-01'], dtype='datetime64[us]', freq=None)

In [67]:
pd.Series(dt_index)

0   2023-01-01
1   2022-01-01
2   2021-01-01
dtype: datetime64[us]

In [68]:
# or index in a seris
pd.Series([1,2,3] , index=dt_index)

2023-01-01    1
2022-01-01    2
2021-01-01    3
dtype: int64

**date_range Function**

In [69]:
# generate daily dates in a given range
pd.date_range(start='2026-9-4' , end='2026-9-20'  , freq='D')

DatetimeIndex(['2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07',
               '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11',
               '2026-09-12', '2026-09-13', '2026-09-14', '2026-09-15',
               '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-19',
               '2026-09-20'],
              dtype='datetime64[us]', freq='D')

In [70]:
# D For each day 2D for skipping 1day 3D to skip 2 days and so on
pd.date_range(start='2026-9-4' , end='2026-9-14'  , freq='2D')

DatetimeIndex(['2026-09-04', '2026-09-06', '2026-09-08', '2026-09-10',
               '2026-09-12', '2026-09-14'],
              dtype='datetime64[us]', freq='2D')

In [ ]:
# B -> business days
pd.date_range(start='2026-09-04' , end='2026-09-14' , freq='B') # skips saturdyas and sundays

DatetimeIndex(['2026-09-04', '2026-09-07', '2026-09-08', '2026-09-09',
               '2026-09-10', '2026-09-11', '2026-09-14'],
              dtype='datetime64[us]', freq='B')

In [77]:
# B -> business days
pd.date_range(start='2026-09-04' , end='2026-09-14' , freq='W')  # WEEK SUNDYAS by default
pd.date_range(start='2026-09-04' , end='2026-09-14' , freq='W-MON') # WEEK MONDAYS
pd.date_range(start='2026-09-04' , end='2026-09-14' , freq='W-FRI')

DatetimeIndex(['2026-09-04', '2026-09-11'], dtype='datetime64[us]', freq='W-FRI')

In [ ]:
# h -> Hourly data(factor)
pd.date_range(start='2026-09-04' , end='2026-09-05' , freq='h')

DatetimeIndex(['2026-09-04 00:00:00', '2026-09-04 01:00:00',
               '2026-09-04 02:00:00', '2026-09-04 03:00:00',
               '2026-09-04 04:00:00', '2026-09-04 05:00:00',
               '2026-09-04 06:00:00', '2026-09-04 07:00:00',
               '2026-09-04 08:00:00', '2026-09-04 09:00:00',
               '2026-09-04 10:00:00', '2026-09-04 11:00:00',
               '2026-09-04 12:00:00', '2026-09-04 13:00:00',
               '2026-09-04 14:00:00', '2026-09-04 15:00:00',
               '2026-09-04 16:00:00', '2026-09-04 17:00:00',
               '2026-09-04 18:00:00', '2026-09-04 19:00:00',
               '2026-09-04 20:00:00', '2026-09-04 21:00:00',
               '2026-09-04 22:00:00', '2026-09-04 23:00:00',
               '2026-09-05 00:00:00'],
              dtype='datetime64[us]', freq='h')

In [83]:
pd.date_range(start='2026-09-04' , end='2026-09-05' , freq='12h')

DatetimeIndex(['2026-09-04 00:00:00', '2026-09-04 12:00:00',
               '2026-09-05 00:00:00'],
              dtype='datetime64[us]', freq='12h')

In [87]:
# M -> Month end
pd.date_range(start='2023/1/5',end='2023/2/28',freq='MS')

DatetimeIndex(['2023-02-01'], dtype='datetime64[us]', freq='MS')

Month End: Use 'ME' instead of 'M'

Month Start: Remains 'MS'

Quarter End: Use 'QE' instead of 'Q'

Quarter Start: Remains 'QS'

Year End: Use 'YE' instead of 'Y' or 'A'

Year Start: Use 'YS' instead of 'YS' or 'AS'

In [88]:
# using periods(number of results)  -> more suitable for generating new data
pd.date_range(start='2026/9/4' , periods=10 , freq='D')

DatetimeIndex(['2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07',
               '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11',
               '2026-09-12', '2026-09-13'],
              dtype='datetime64[us]', freq='D')

In [89]:
pd.date_range(start='2026/9/4' , periods=10 , freq='2D')

DatetimeIndex(['2026-09-04', '2026-09-06', '2026-09-08', '2026-09-10',
               '2026-09-12', '2026-09-14', '2026-09-16', '2026-09-18',
               '2026-09-20', '2026-09-22'],
              dtype='datetime64[us]', freq='2D')

In [90]:
pd.date_range(start='2026/9/4' , periods=10 , freq='MS')

DatetimeIndex(['2026-10-01', '2026-11-01', '2026-12-01', '2027-01-01',
               '2027-02-01', '2027-03-01', '2027-04-01', '2027-05-01',
               '2027-06-01', '2027-07-01'],
              dtype='datetime64[us]', freq='MS')

# to_datetime function

converts an existing objects to pandas timestamp/datetimeindex object

In [95]:
arr = pd.Series(['2026/09/04' , '2026/09/05' , '2026/09/06'])
print(arr.dtype)
type(arr[0])

str

str

In [96]:
arr = pd.to_datetime(arr)
print(arr.dtype)
type(arr[0])

datetime64[us]

pandas.Timestamp

In [97]:
# dt accessor like str for string vectorized operations
arr.dt.month_name()

0    September
1    September
2    September
dtype: str

In [98]:
arr.dt.year

0    2026
1    2026
2    2026
dtype: int32

In [99]:
# with errors
s = pd.Series(['2026/1/1','2025/1/1','2021/130/1']) # '2021/130/1' wrong date
pd.to_datetime(s)

ValueError: time data "2021/130/1" doesn't match format "%Y/%m/%d". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [101]:
# SOLUTION
s = pd.to_datetime(s  , errors='coerce') # skips wrong dates in caluculations
s

0   2026-01-01
1   2025-01-01
2          NaT
dtype: datetime64[us]

# Expenses Data-Set

In [106]:
df = pd.read_csv('C:/Users/Lenovo/Desktop/Python/Pandas/DateTime,Pivot Table ,String opr in Pandas/expense_data.csv')

In [107]:
df.head(3)

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0

In [108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            277 non-null    str
 1   Account         277 non-null    str
 2   Category        277 non-null    str
 3   Subcategory     0 non-null      float64
 4   Note            273 non-null    str
 5   INR             277 non-null    float64
 6   Income/Expense  277 non-null    str
 7   Note.1          0 non-null      float64
 8   Amount          277 non-null    float64
 9   Currency        277 non-null    str
 10  Account.1       277 non-null    float64
dtypes: float64(5), str(6)
memory usage: 23.9 KB

In [109]:
df['Date']= pd.to_datetime(df['Date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            277 non-null    datetime64[us]
 1   Account         277 non-null    str
 2   Category        277 non-null    str
 3   Subcategory     0 non-null      float64
 4   Note            273 non-null    str
 5   INR             277 non-null    float64
 6   Income/Expense  277 non-null    str
 7   Note.1          0 non-null      float64
 8   Amount          277 non-null    float64
 9   Currency        277 non-null    str
 10  Account.1       277 non-null    float64
dtypes: datetime64[us](1), float64(5), str(5)
memory usage: 23.9 KB

In [112]:
# NOW YOU CAN FILTER EASILY
# Calculate 2022 category wise expense
df['year'] = df.Date.dt.year
temp_df = df[df['year'] == 2022]

In [116]:
temp_df.groupby('Category')[['INR']].sum()

                     INR
Category
Allowance        1000.00
Apparel           798.00
Education        1400.00
Food            14887.36
Household        7388.00
Other           34078.00
Salary           8000.00
Social Life      2000.00
Transportation   7958.80

In [115]:
# OR
temp_df.pivot_table(index='Category' , values='INR' , aggfunc='sum')

                     INR
Category
Allowance        1000.00
Apparel           798.00
Education        1400.00
Food            14887.36
Household        7388.00
Other           34078.00
Salary           8000.00
Social Life      2000.00
Transportation   7958.80