In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({
    'name':['abdul' , 'hamza' , 'ali'],
    'age' : [20 ,21 ,19] ,
    'city' : ['Lhr' ,'Skp' ,'Mlt']
})

In [7]:
df.set_index('name').loc['abdul']['age']

np.int64(20)

**MultiIndexing**

In [8]:
# try to create a multiIndexing  series 
multi_index = [('cse',2022) , ('cse',2023) ,('cse',2024) ,('cse',2025) ,('ecs',2022) ,('ecs',2023) ,('ecs',2024),('ecs',2025)]
ser1 = pd.Series([1,2,3,4,5,6,7,8]  , index= multi_index)
ser1

(cse, 2022)    1
(cse, 2023)    2
(cse, 2024)    3
(cse, 2025)    4
(ecs, 2022)    5
(ecs, 2023)    6
(ecs, 2024)    7
(ecs, 2025)    8
dtype: int64

In [ ]:
# this is not true multi_indexing
ser1[('cse' ,2024)] # valid
ser1['cse'] # not valid

KeyError: 'cse'

**Right way to create multi_indexing**

In [12]:
# The solution -> multiindex series(also known as Hierarchical Indexing)
# multiple index levels within a single index

In [30]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
multi_index1 = pd.MultiIndex.from_tuples(multi_index)
print(multi_index1.levels)
print(type(multi_index1.levels))
print(type(multi_index1))

[['cse', 'ecs'], [2022, 2023, 2024, 2025]]
<class 'pandas.api.typing.FrozenList'>
<class 'pandas.MultiIndex'>

In [31]:
print(multi_index1.levels[0])
print(type(multi_index1.levels[0]))

Index(['cse', 'ecs'], dtype='str')
<class 'pandas.Index'>

In [28]:
# 2nd way -> pd.MultiIndex.from_product
multi_index_2 = pd.MultiIndex.from_product([['cse' , 'ecs'] , [2022 ,2023 , 2024 , 2025]])
multi_index_2

MultiIndex([('cse', 2022),
            ('cse', 2023),
            ('cse', 2024),
            ('cse', 2025),
            ('ecs', 2022),
            ('ecs', 2023),
            ('ecs', 2024),
            ('ecs', 2025)],
           )

In [34]:
# Now lets create multi_index 
ser2 = pd.Series([1,2,3,4,5,6,7,8] , index= multi_index1)
ser2

cse  2022    1
     2023    2
     2024    3
     2025    4
ecs  2022    5
     2023    6
     2024    7
     2025    8
dtype: int64

In [35]:
ser2['cse']

2022    1
2023    2
2024    3
2025    4
dtype: int64

In [36]:
ser2.ndim

1

In [39]:
# converting multi_index series into dataFrame 
temp_df = ser2.unstack()
temp_df

     2022  2023  2024  2025
cse     1     2     3     4
ecs     5     6     7     8

In [40]:
# converting dataframe to multi_index series
temp_df.stack()

cse  2022    1
     2023    2
     2024    3
     2025    4
ecs  2022    5
     2023    6
     2024    7
     2025    8
dtype: int64

In [42]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multi_index1,
    columns = ['avg_package','students']
)
branch_df1

          avg_package  students
cse 2022            1         2
    2023            3         4
    2024            5         6
    2025            7         8
ecs 2022            9        10
    2023           11        12
    2024           13        14
    2025           15        16

In [44]:
branch_df1.loc['cse']

      avg_package  students
2022            1         2
2023            3         4
2024            5         6
2025            7         8

In [ ]:
print(type(branch_df1['students'])) 
branch_df1['students'] # multi_index series

<class 'pandas.Series'>

cse  2022     2
     2023     4
     2024     6
     2025     8
ecs  2022    10
     2023    12
     2024    14
     2025    16
Name: students, dtype: int64

In [51]:
# pandas internally treat columns and indexes in same way
df = pd.DataFrame(
     [[6 ,74 , 6, 56],
      [5.7 ,89 , 5.7 ,67],
      [5.11 ,58 , 5.11 , 46],
      [5.5 ,65 , 5.5 , 56]] ,

    index=[2023,2024,2025,2026],
    columns=pd.MultiIndex.from_product([['Lahore' ,'Karachi'] , ['Height' , 'Avg.Weight']])
)

In [52]:
df

     Lahore            Karachi
     Height Avg.Weight  Height Avg.Weight
2023   6.00         74    6.00         56
2024   5.70         89    5.70         67
2025   5.11         58    5.11         46
2026   5.50         65    5.50         56

In [58]:
df.loc[2023]

Lahore   Height         6.0
         Avg.Weight    74.0
Karachi  Height         6.0
         Avg.Weight    56.0
Name: 2023, dtype: float64

In [60]:
branch_df1

          avg_package  students
cse 2022            1         2
    2023            3         4
    2024            5         6
    2025            7         8
ecs 2022            9        10
    2023           11        12
    2024           13        14
    2025           15        16

In [61]:
branch_df1.unstack()

    avg_package                students
           2022 2023 2024 2025     2022 2023 2024 2025
cse           1    3    5    7        2    4    6    8
ecs           9   11   13   15       10   12   14   16

In [ ]:
branch_df1.unstack().unstack() # single row or column is a series(here multi_index series)

avg_package  2022  cse     1
                   ecs     9
             2023  cse     3
                   ecs    11
             2024  cse     5
                   ecs    13
             2025  cse     7
                   ecs    15
students     2022  cse     2
                   ecs    10
             2023  cse     4
                   ecs    12
             2024  cse     6
                   ecs    14
             2025  cse     8
                   ecs    16
dtype: int64

In [66]:
# now stack
m_ser = branch_df1.unstack()
m_ser

    avg_package                students
           2022 2023 2024 2025     2022 2023 2024 2025
cse           1    3    5    7        2    4    6    8
ecs           9   11   13   15       10   12   14   16

In [69]:
m_ser.stack()

          avg_package  students
cse 2022            1         2
    2023            3         4
    2024            5         6
    2025            7         8
ecs 2022            9        10
    2023           11        12
    2024           13        14
    2025           15        16

In [72]:
m_ser.stack().stack()

cse  2022  avg_package     1
           students        2
     2023  avg_package     3
           students        4
     2024  avg_package     5
           students        6
     2025  avg_package     7
           students        8
ecs  2022  avg_package     9
           students       10
     2023  avg_package    11
           students       12
     2024  avg_package    13
           students       14
     2025  avg_package    15
           students       16
dtype: int64

In [73]:
branch_df1

          avg_package  students
cse 2022            1         2
    2023            3         4
    2024            5         6
    2025            7         8
ecs 2022            9        10
    2023           11        12
    2024           13        14
    2025           15        16

In [74]:
# head() & tail()
# info
# sample
# shape
branch_df1.head(1)

          avg_package  students
cse 2022            1         2

In [75]:
branch_df1.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2022)) to ('ecs', np.int64(2025))
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   avg_package  8 non-null      int64
 1   students     8 non-null      int64
dtypes: int64(2)
memory usage: 504.0+ bytes

In [80]:
branch_df1.loc[('cse',2022):('ecs' ,2022) : 2]

          avg_package  students
cse 2022            1         2
    2024            5         6
ecs 2022            9        10

In [82]:
branch_df1.iloc[0]

avg_package    1
students       2
Name: (cse, 2022), dtype: int64

In [81]:
branch_df1['avg_package'][:4]

cse  2022    1
     2023    3
     2024    5
     2025    7
Name: avg_package, dtype: int64

In [83]:
branch_df1

          avg_package  students
cse 2022            1         2
    2023            3         4
    2024            5         6
    2025            7         8
ecs 2022            9        10
    2023           11        12
    2024           13        14
    2025           15        16

In [84]:
branch_df1.iloc[ : , 1]

cse  2022     2
     2023     4
     2024     6
     2025     8
ecs  2022    10
     2023    12
     2024    14
     2025    16
Name: students, dtype: int64

In [88]:
df

     Lahore            Karachi
     Height Avg.Weight  Height Avg.Weight
2023   6.00         74    6.00         56
2024   5.70         89    5.70         67
2025   5.11         58    5.11         46
2026   5.50         65    5.50         56

In [89]:
df.iloc[:2 , ::2]

     Lahore Karachi
     Height  Height
2023    6.0     6.0
2024    5.7     5.7

In [108]:
df.iloc[: , [0,3]]

     Lahore    Karachi
     Height Avg.Weight
2023   6.00         56
2024   5.70         67
2025   5.11         46
2026   5.50         56

In [111]:
df.swaplevel(axis=1)

     Height Avg.Weight  Height Avg.Weight
     Lahore     Lahore Karachi    Karachi
2023   6.00         74    6.00         56
2024   5.70         89    5.70         67
2025   5.11         58    5.11         46
2026   5.50         65    5.50         56

**More  complex data**

In [136]:
# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multi_index1,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2022           1        2           0        0
    2023           3        4           0        0
    2024           5        6           0        0
    2025           7        8           0        0
ecs 2022           9       10           0        0
    2023          11       12           0        0
    2024          13       14           0        0
    2025          15       16           0        0

**Stacking & Unstacking**

In [116]:
branch_df3.stack()

                      delhi  mumbai
cse 2022 avg_package      1       0
         students         2       0
    2023 avg_package      3       0
         students         4       0
    2024 avg_package      5       0
         students         6       0
    2025 avg_package      7       0
         students         8       0
ecs 2022 avg_package      9       0
         students        10       0
    2023 avg_package     11       0
         students        12       0
    2024 avg_package     13       0
         students        14       0
    2025 avg_package     15       0
         students        16       0

In [117]:
branch_df3.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2022)) to ('ecs', np.int64(2025))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 820.0+ bytes

In [145]:
branch_df3[('mumbai' ,'students')] = 5

In [144]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2022           1        2           0        5
    2023           3        4           0        5
    2024           5        6           0        5
    2025           7        8           0        5
ecs 2022           9       10           0        5
    2023          11       12           0        5
    2024          13       14           0        5
    2025          15       16           0        5

In [150]:
# for not single column use .loc or .iloc
branch_df3.loc[('cse',2022) : ('cse',2025):2 , ('mumbai' ,'students')] = np.nan

In [151]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2022           1        2           0      NaN
    2023           3        4           0      5.0
    2024           5        6           0      NaN
    2025           7        8           0      5.0
ecs 2022           9       10           0      5.0
    2023          11       12           0      5.0
    2024          13       14           0      5.0
    2025          15       16           0      5.0

In [154]:
simple_df = pd.DataFrame({
    'name' : ['abdul' , 'hamza' , 'ali'] ,
    'avg_run' : [34,42,32]
})

In [155]:
simple_df

    name  avg_run
0  abdul       34
1  hamza       42
2    ali       32

In [ ]:
simple_df.iloc[::2]['avg_run'] = 5 # notthing in original one as it becomes a copy

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_23160\3503184428.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  simple_df.iloc[::2]['avg_run'] = 5

In [159]:
simple_df.loc[::2 ,'avg_run'] = 50

In [160]:
simple_df

    name  avg_run
0  abdul       50
1  hamza       42
2    ali       50

In [161]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2022           1        2           0      NaN
    2023           3        4           0      5.0
    2024           5        6           0      NaN
    2025           7        8           0      5.0
ecs 2022           9       10           0      5.0
    2023          11       12           0      5.0
    2024          13       14           0      5.0
    2025          15       16           0      5.0

In [162]:
branch_df3.head()

               delhi               mumbai
         avg_package students avg_package students
cse 2022           1        2           0      NaN
    2023           3        4           0      5.0
    2024           5        6           0      NaN
    2025           7        8           0      5.0
ecs 2022           9       10           0      5.0

In [166]:
branch_df3[('mumbai' , 'students')][branch_df3[('mumbai' , 'students')].isna()]

cse  2022   NaN
     2024   NaN
Name: (mumbai, students), dtype: float64

In [168]:
branch_df3.shape

(8, 4)

In [169]:
branch_df3.head(3)

               delhi               mumbai
         avg_package students avg_package students
cse 2022           1        2           0      NaN
    2023           3        4           0      5.0
    2024           5        6           0      NaN

In [170]:
# single row
branch_df3.loc[('cse' , 2022)]

delhi   avg_package    1.0
        students       2.0
mumbai  avg_package    0.0
        students       NaN
Name: (cse, 2022), dtype: float64

In [175]:
# fetch cse 2023 and ecs 2023
branch_df3.iloc[1:6:4].loc[: , 'mumbai']

          avg_package  students
cse 2023            0       5.0
ecs 2023            0       5.0

In [177]:
# sort index
branch_df3.sort_index(ascending=False)

               delhi               mumbai
         avg_package students avg_package students
ecs 2025          15       16           0      5.0
    2024          13       14           0      5.0
    2023          11       12           0      5.0
    2022           9       10           0      5.0
cse 2025           7        8           0      5.0
    2024           5        6           0      NaN
    2023           3        4           0      5.0
    2022           1        2           0      NaN

In [178]:
branch_df3.sort_index(ascending=[True, False])

               delhi               mumbai
         avg_package students avg_package students
cse 2025           7        8           0      5.0
    2024           5        6           0      NaN
    2023           3        4           0      5.0
    2022           1        2           0      NaN
ecs 2025          15       16           0      5.0
    2024          13       14           0      5.0
    2023          11       12           0      5.0
    2022           9       10           0      5.0

In [ ]:
# branch_df3.sort_index(level=0 , ascending=False) -> DIFF of [] around false (simple false lead to apply at all)
branch_df3.sort_index(level=0 , ascending=[False])

               delhi               mumbai
         avg_package students avg_package students
ecs 2022           9       10           0      5.0
    2023          11       12           0      5.0
    2024          13       14           0      5.0
    2025          15       16           0      5.0
cse 2022           1        2           0      NaN
    2023           3        4           0      5.0
    2024           5        6           0      NaN
    2025           7        8           0      5.0

In [181]:
# multiindex dataframe(col) -> transpose
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2022           1        2           0      NaN
    2023           3        4           0      5.0
    2024           5        6           0      NaN
    2025           7        8           0      5.0
ecs 2022           9       10           0      5.0
    2023          11       12           0      5.0
    2024          13       14           0      5.0
    2025          15       16           0      5.0

In [182]:
branch_df3.T

                    cse                  ecs
                   2022 2023 2024 2025  2022  2023  2024  2025
delhi  avg_package  1.0  3.0  5.0  7.0   9.0  11.0  13.0  15.0
       students     2.0  4.0  6.0  8.0  10.0  12.0  14.0  16.0
mumbai avg_package  0.0  0.0  0.0  0.0   0.0   0.0   0.0   0.0
       students     NaN  5.0  NaN  5.0   5.0   5.0   5.0   5.0

In [ ]:
# swaplevel 
branch_df3.swaplevel() # axis= 0 by default for indexes

               delhi               mumbai
         avg_package students avg_package students
2022 cse           1        2           0      NaN
2023 cse           3        4           0      5.0
2024 cse           5        6           0      NaN
2025 cse           7        8           0      5.0
2022 ecs           9       10           0      5.0
2023 ecs          11       12           0      5.0
2024 ecs          13       14           0      5.0
2025 ecs          15       16           0      5.0

In [184]:
branch_df3.swaplevel(axis=1)

         avg_package students avg_package students
               delhi    delhi      mumbai   mumbai
cse 2022           1        2           0      NaN
    2023           3        4           0      5.0
    2024           5        6           0      NaN
    2025           7        8           0      5.0
ecs 2022           9       10           0      5.0
    2023          11       12           0      5.0
    2024          13       14           0      5.0
    2025          15       16           0      5.0

**Long VS Wide Data**

**WIDE :-** Usually single row for a data point with multiple columns as its attributes (no.of cols > no.of rows)

**Long :-** Usually many rows are present as attributes related to a single data point (no.of rows > no.of cols)

In [187]:
# MELT FUNCTION (convert wide to long)
df1 = pd.DataFrame({
    'name' : ['abdul' , 'hamza'] ,
    'height': [5.11 , 5.9] ,
    'weight': [58 , 64]
})
df1

    name  height  weight
0  abdul    5.11      58
1  hamza    5.90      64

In [ ]:
# using melt 
pd.melt(df1) # not meaning full but in long format

  variable  value
0     name  abdul
1     name  hamza
2   height   5.11
3   height    5.9
4   weight     58
5   weight     64

In [ ]:
# Correct way
pd.melt(df1 , id_vars='name') # prevent name column to be in long format

    name variable  value
0  abdul   height   5.11
1  hamza   height   5.90
2  abdul   weight  58.00
3  hamza   weight  64.00

In [192]:
# more suitable to change names
melt_df = pd.melt(df1 , id_vars='name' , var_name='height&weight' )
melt_df

    name height&weight  value
0  abdul        height   5.11
1  hamza        height   5.90
2  abdul        weight  58.00
3  hamza        weight  64.00

In [196]:
print(pd.DataFrame({'cse':[120]}))
pd.DataFrame({'cse':[120]}).melt()

   cse
0  120

  variable  value
0      cse    120

In [197]:
# next data 
pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]})

   cse  ece  mech
0  120  100    50

In [198]:
melt_2 = pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]}).melt(var_name='branch' , value_name='students')
melt_2

  branch  students
0    cse       120
1    ece       100
2   mech        50

In [199]:
pd.DataFrame(
    {
        'branch':['cse','ece','mech'],
        '2020':[100,150,60],
        '2021':[120,130,80],
        '2022':[150,140,70]
    }
)

  branch  2020  2021  2022
0    cse   100   120   150
1    ece   150   130   140
2   mech    60    80    70

In [202]:
pd.DataFrame(
    {
        'branch':['cse','ece','mech'],
        '2020':[100,150,60],
        '2021':[120,130,80],
        '2022':[150,140,70]
    }
).melt(id_vars='branch' , var_name='year' , value_name='students')

  branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        60
3    cse  2021       120
4    ece  2021       130
5   mech  2021        80
6    cse  2022       150
7    ece  2022       140
8   mech  2022        70

**Covid_base real world data set**

In [220]:
deaths = pd.read_csv('C:/Users/Lenovo/Desktop/Python/Pandas/MultiIndexDataFrame/time_series_covid19_deaths_global.csv')
confirmed_cases = pd.read_csv('C:/Users/Lenovo/Desktop/Python/Pandas/MultiIndexDataFrame/time_series_covid19_confirmed_global.csv')

In [204]:
deaths.head(2)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595

In [205]:
confirmed_cases.head(2)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812

In [ ]:
# YOUR MANAGER SAYS YOU TO MAKE A SINGLE TABLE FROM THESE DATASETS
# FORMAT : 
#   Country/Region |	date |	num_cases |	num_deaths

In [221]:
deaths = deaths.melt(id_vars=['Province/State','Country/Region','Lat','Long'] , var_name='date' , value_name='num_of_deaths' )
confirmed_cases = confirmed_cases.melt(id_vars=['Province/State','Country/Region','Lat','Long'] , var_name='date' , value_name='num_of_confirmed_cases' )

In [222]:
deaths.head(3)

  Province/State Country/Region       Lat       Long     date  num_of_deaths
0            NaN    Afghanistan  33.93911  67.709953  1/22/20              0
1            NaN        Albania  41.15330  20.168300  1/22/20              0
2            NaN        Algeria  28.03390   1.659600  1/22/20              0

In [224]:
confirmed_cases.head(3)

,Province/State,Country/Region,Lat,Long,date,num_of_confirmed_cases
0,NaN,Afghanistan,33.93911,67.709953,1/22/20,0
1,NaN,Albania,41.15330,20.168300,1/22/20,0
2,NaN,Algeria,28.03390,1.659600,1/22/20,0

In [226]:
data = deaths.merge(confirmed_cases , on=['Province/State','Country/Region','Lat','Long','date'] )

In [229]:
data[['Province/State' , 'Country/Region' ,'date' ,'num_of_confirmed_cases' , 'num_of_deaths']].sort_values(by=['date' ,'num_of_confirmed_cases','num_of_deaths'] ,ascending=[True ,False,False])

,Province/State,Country/Region,date,num_of_confirmed_cases,num_of_deaths
99965,NaN,US,1/1/21,20394863,352760
99853,NaN,India,1/1/21,10305788,149218
99736,NaN,Brazil,1/1/21,7703971,195541
99926,NaN,Russia,1/1/21,3153960,56798
99836,NaN,France,1/1/21,2636045,64399
...,...,...,...,...,...
277904,NaN,MS Zaandam,9/9/22,9,2
278004,Pitcairn Islands,United Kingdom,9/9/22,4,0
277890,NaN,"Korea, North",9/9/22,1,6
277771,Diamond Princess,Canada,9/9/22,0,1
277997,Channel Islands,United Kingdom,9/9/22,0,0